### ISSUE TITLE
Deploy to AWS

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/reddit-bot#1]
I ran the bot for a bit on my own computer.
Here is the bot account: https://www.reddit.com/user/openseadragonizer/

Except for some `praw.errors.RateLimitExceeded: you are doing that too much. try again in 9 minutes. on field ratelimit` errors, it seems to work ok.
People seems to generally like it. This makes some funny/awkard situations where you can zoom on people's nose hair and such.

So the next step is to actually deploy it for good.

**Comment by avandecreme** [comment]
Ok, I deployed it.
I also restricted to 3 subreddits for now (earthporn, mapporn and space) because having a zoomable version of other subreddits images is too often irrelevant.
We can of course add others later.

**Comment by iangilman** [comment]
This is awesome! I guess it's ready to be publicized?

**Comment by avandecreme** [comment]
Yep.
After a few days, the bot is having mixed feedback.
Some find it useless (I suspect mobile device users who already have zooming available), others like it.

It also got banned from earthporn for weird rehosting policies:

> your bot appears to be stealing content and rehosting it on your servers. We are against that sort of thing.

When explained that the bot is doing no rehosting, here is the answer:

> We do not encourage the sharing of reddit's non-authorized rehosted links, only of the original source itself. You may not be the one rehosting, but you are sharing the link to a rehost.

So the bot is now posting to /r/space and /r/mapporn.

**Comment by iangilman** [comment]
It's certainly a grand experiment! I figure as long as some people like it the others can ignore it. 

Sounds like the earthporn folks still don't quite get it from a technical standpoint, but I suppose it doesn't matter if it just feels wrong to them.

I guess we should be on the lookout for additional subreddits that could use it.

**Comment by iangilman** [comment]
Okay, I've tweeted about it: https://twitter.com/iangilman/status/739860738349486080

BTW, @avandecreme do you have a Twitter handle I can tag to give you credit (if you want)?

**Comment by avandecreme** [comment]
Nope, I don't use twitter, but that's great that you are taking care of it :+1:
